
import { MONOSPACE_FONTS, SANS_SERIF_FONTS, SERIF_FONTS } from "@/__fixtures__/typographies";
import { DEFAULTS as CARD_DEFAULT_CONFIG, DEFAULTS } from "@/components/Card/constants";
import type { CardConfig } from "@/components/Card/types";

export const DEFAULT_CONFIG: CardConfig = {
	...CARD_DEFAULT_CONFIG,
	properties: [
    'note.author',
  ],
} satisfies Partial<CardConfig>;

export const FULL_CONFIG: CardConfig = {
	...DEFAULT_CONFIG,
	layout: "horizontal",
	shape: "square",
	cardSize: 400,
	imageProperty: "note.banner",
	imageAspectRatio: 0.85,
	imageFit: "cover",
	showTitle: true,
	showPropertyTitles: false,
	properties: ["note.author", "note.published", "note.excerpt"],
	reverseContent: true,
	hoverProperty: "note.url",
	hoverStyle: "overlay",
  linkProperty: undefined,
  titleFont: SERIF_FONTS,
  contentFont: SANS_SERIF_FONTS,
  badgesFont: MONOSPACE_FONTS,
  iconProperty: 'note.icon',
  backgroundColorProperty: 'note.color',
  backgroundColorApplyTo: 'both',
} satisfies Partial<CardConfig>;

export const HORIZONTAL_LAYOUT_CONFIG: CardConfig = {
  ...DEFAULT_CONFIG,
  layout: 'horizontal',
  shape: 'square',
  hoverProperty: 'note.url',
  hoverStyle: 'overlay',
  properties: [
    'note.author',
    'note.published',
    'note.excerpt',
  ],
  imageProperty: 'note.banner',
  imageAspectRatio: 0.85,
  cardSize: 400,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  linkProperty: undefined,
}

export const OVERLAY_LAYOUT_CONFIG: CardConfig = {
  layout: 'overlay',
  shape: 'square',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1.5,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: true,
  contentMaxLength: 200,
  overlayContentVisibility: 'always',
  badgeProperty: 'note.rating',
  badgeIcon: 'star',
  badgeColor: '#D0A215',
  tilt: DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
}

export const OVERLAY_ON_HOVER_LAYOUT_CONFIG: CardConfig = {
  ...OVERLAY_LAYOUT_CONFIG,
  overlayContentVisibility: 'hover',
}

export const CIRCLE_SHAPE_CONFIG: CardConfig = {
  layout: 'overlay',
  shape: 'circle',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: false,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'always',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
}


export const ROUNDED_SHAPE_CONFIG: CardConfig = {
  layout: 'overlay',
  shape: 'rounded',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'hover',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
}

export const POLAROID_LAYOUT_CONFIG: CardConfig = {
  ...DEFAULT_CONFIG,
  layout: 'polaroid',
  cardSize: 280,
  imageAspectRatio: 1,
  imageProperty: 'note.banner',
  showTitle: true,
  showPropertyTitles: false,
  properties: [],
  tilt: DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
}
