import { MONOSPACE_FONTS, SANS_SERIF_FONTS, SERIF_FONTS } from "@/__fixtures__/typographies";
import { DEFAULTS as CARD_DEFAULTS } from "@/components/Card/constants";

import type { ProjectFoldersConfig } from "../types";

export const DEFAULT_CONFIG: ProjectFoldersConfig = {
	groupIconProperty: undefined,
	groupColorProperty: undefined,
	groupShape: "folder",
	groupTitlePosition: "outside",
	...CARD_DEFAULTS,
	properties: ["note.author"],
};

export const FULL_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
	layout: "horizontal",
	shape: "square",
	cardSize: 400,
	imageProperty: "note.banner",
	imageAspectRatio: 0.85,
	imageFit: "cover",
	showTitle: true,
	showPropertyTitles: false,
	properties: ["note.author", "note.published", "note.excerpt"],
	reverseContent: true,
  linkProperty: undefined,
  titleFont: SERIF_FONTS,
  contentFont: SANS_SERIF_FONTS,
  badgesFont: MONOSPACE_FONTS,
  iconProperty: 'note.icon',
  backgroundColorProperty: 'note.color',
  backgroundColorApplyTo: 'both',
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
  groupTitlePosition: "inside",
};

export const NOTEBOOK_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
	groupShape: "notebook",
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
  groupTitlePosition: "inside",
};

export const HORIZONTAL_LAYOUT_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
  layout: 'horizontal',
  shape: 'square',
  properties: [
    'note.author',
    'note.published',
    'note.excerpt',
  ],
  imageProperty: 'note.banner',
  imageAspectRatio: 0.85,
  cardSize: 400,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  linkProperty: undefined,
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
};

export const OVERLAY_LAYOUT_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
  layout: 'overlay',
  shape: 'square',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1.5,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: true,
  contentMaxLength: 200,
  overlayContentVisibility: 'hover',
  badgeProperty: 'note.rating',
  badgeIcon: 'star',
  badgeColor: '#D0A215',
  tilt: CARD_DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
};

export const POLAROID_LAYOUT_CONFIG: ProjectFoldersConfig = {
  ...DEFAULT_CONFIG,
  layout: 'polaroid',
  cardSize: 280,
  imageAspectRatio: 1,
  imageProperty: 'note.banner',
  showTitle: true,
  showPropertyTitles: false,
  properties: [],
  tilt: CARD_DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
};

// === TITLE POSITION CONFIGS ===

export const TITLE_INSIDE_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
	groupTitlePosition: "inside",
	groupIconProperty: "note.icon",
	groupColorProperty: "note.color",
};

export const TITLE_HIDDEN_CONFIG: ProjectFoldersConfig = {
	...DEFAULT_CONFIG,
	groupTitlePosition: "none",
	groupIconProperty: "note.icon",
	groupColorProperty: "note.color",
};

// === SHAPE CONFIGS ===

export const CIRCLE_SHAPE_CONFIG: ProjectFoldersConfig = {
  layout: 'vertical',
  shape: 'circle',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: false,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'always',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: CARD_DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
};

export const ROUNDED_SHAPE_CONFIG: ProjectFoldersConfig = {
  layout: 'overlay',
  shape: 'rounded',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'hover',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: CARD_DEFAULTS.tilt,
  linkProperty: undefined,
  backgroundColorProperty: undefined,
  backgroundColorApplyTo: undefined,
  iconProperty: undefined,
  badgesFont: undefined,
  titleFont: undefined,
  contentFont: undefined,
  groupIconProperty: 'note.icon',
  groupColorProperty: 'note.color',
};
